### ISSUE TITLE
信息收集不全

### ISSUE THREAD

**Issue by 0xlwoe21k** [bytedance/Elkeid-HUB#10]
如下 图所示，针对59 类型的规则，发现客户端信息收集不全，请问有哪些可能的原因呢？
![image](https://user-images.githubusercontent.com/8515198/172111609-3041d139-df8a-4417-8a25-4eebcdeb270c.png)

**Comment by EBWi11** [comment]
59数据采集的网络数据（sip/dip/sport/dport/socket_pid/sa_family）是有遍历深度的（fd & parent process），如果超过最大遍历上限依然采集不到会置空
