### ISSUE TITLE
sip出现了不存在的IP

### ISSUE THREAD

**Issue by 0xlwoe21k** [bytedance/Elkeid-HUB#11]
本机IP为：10.50.11.48
内核版本： 2.6.32-696.el6.x86_64
规则：读取特定文件告警
![image](https://user-images.githubusercontent.com/8515198/172133534-60b6eae2-3ac0-4dde-887c-4fd28cfd8818.png)
![image](https://user-images.githubusercontent.com/8515198/172133590-6b9efd8b-c69f-465f-868f-01a6eab4b8c1.png)

其中【8.136.255.255】为不存在的IP。

问：为什么会出现此IP，可能的情况是什么？

**Comment by EBWi11** [comment]
目前猜测是在特定内核下该参数(sip)错误，具体涉及版本还需要进一步测试。测试结果出来后会同步，感谢。
