### ISSUE TITLE
执行./bootstrap.sh 提示stat py/elkeid.sock: no such file or directory 

### ISSUE THREAD

**Issue by crazyydevil** [bytedance/Elkeid-HUB#8]
下载解压后，修改了config里的input，out对应的kafka地址。执行./bootstrap.sh，报了panic: [AgentSmith INIT] CUSTOM PLUGIN INIT FAILEDplugin process run timeout, List plugin error: stat /root/elkeid/elkeid_hub_community/py/elkeid.sock: no such file or directory 
。按照文档说明去cat py/plugin.stdout，没有该文件
![image](https://user-images.githubusercontent.com/3899020/157191740-ba84c22c-04cd-46f3-a710-fd9dadad63bd.png)

**Comment by UgOrange** [comment]
可以先试着删掉py/.success文件，再执行一次bootstrap.sh重新安装下python环境
如果还不行麻烦再发下log/smith.log和log/smith.log.custom文件

**Comment by crazyydevil** [comment]
删除py/.success后执行还是同样的错误，也没有plugin.stdout。查看了smith.log和smith.log.custom文件如下图所示
![image](https://user-images.githubusercontent.com/3899020/157194733-f0b9d977-9480-4b6e-b7e8-9e481d50531a.png)

**Comment by TaeRoen** [comment]
@crazyydevil  你的py目录缺了好多文件，都没有pypy的执行环境，重新在干净目录解压后运行看看? 中途多等一会
正常情况下py目录有这些文件
~/hub/elkeid_hub_community# ls py
download                                                                                                                             plugin_zip
_elkeid_queue.c                                                                                                                      __pycache__
_elkeid_queue.o                                                                                                                      pypy
_elkeid_queue.pypy37-pp73-x86_64-linux-gnu.so                                                                                        pypy3.7-v7.3.5-linux64
elkeid.sock                                                                                                                          PZozDRmkcmNzddEUVbFVYwaScCaPEDfFNtabHznsUcwGrYDjwxgxHYWoiYNDEZGJLOusZMYdWYnGIoGNhKQIQIKYTwFgtwxWWTGvPShWkJuYINpWxfqwVCAaVInKyTUj.py
jEeeXuOBMlCSWslbicutJFrOtUMFRNZOscmdCvzhvzqBKqLBGmBlfKpxZBeqtfmLbhQMHXKePMtYnNknvvxIrsXzYzLcVgVIDLZZcMrhSLoQikYRkOzHtwXuAylfkDyu.py  queue.h
plugin_log.py                                                                                                                        requirements.txt
plugin_msgpack.py                                                                                                                    run.sh
plugin_redis.py                                                                                                                      start.py
plugin_shm.py                                                                                                                        sthqiWDuarARPqndkeXjroRbJVUlVjFOHZBhnByxlvcQcybBMNkqXCPaHTLWrviEjnXjgGLVxFKnwbYmOfBPWrMabvEHUBVhvVibmReBRJJuOTQAigWHnstvTTAmHphI.py
plugin.stdout                                                                                                                        tmp_requirements.txt
plugin_unzip

**Comment by crazyydevil** [comment]
这些文件是解压出来就有，还是安装过程中产生的

**Comment by TaeRoen** [comment]
@crazyydevil pypy pypy3.7-v7.3.5-linux64 这两个是安装过程中产生的，其他压缩包不存在的，是运行时产生的

**Comment by crazyydevil** [comment]
@TaeRoen 单独安装[Elkeid-HUB]还是一样的，通过ElkeidUP 安装则是正常的，可以使用里面的hub组件

**Comment by TaeRoen** [comment]
@crazyydevil 把新环境下执行 ./bootstrap.sh 的输出贴一下吧，太多的话打包发到群里也行，我们看下

**Comment by crazyydevil** [comment]
@TaeRoen 
![image](https://user-images.githubusercontent.com/3899020/158299620-d88f5db1-adb2-4424-96fd-3eea0c8558b4.png)
![image](https://user-images.githubusercontent.com/3899020/158299634-cacb3fd3-e6a1-41ab-81c6-37e346ec8843.png)
![image](https://user-images.githubusercontent.com/3899020/158299612-42c10885-44f4-4a68-b9b9-3e3bf515c0b9.png)
![image](https://user-images.githubusercontent.com/3899020/158299602-458b5541-e35b-48eb-be84-bb252d1fb591.png)

**Comment by crazyydevil** [comment]
这几天没上来看，贴图贴了，顺序反了，从上面往上看，在纯净的环境下面 @TaeRoen

**Comment by TaeRoen** [comment]
看样子是缺少bzip2相关依赖,导致pypy执行环境没解压出来

**Comment by crazyydevil** [comment]
@TaeRoen 嗯，可以了。确实是缺少了依赖。
